name: Auto Release

on:
    push:
        branches:
            - main
        paths:
            - "release/severitium.user.js"

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Extract version from severitium.user.js
              id: extract
              run: |
                  version=$(grep -oP '@version\s+\K[\w.+-]+' release/severitium.user.js)
                  echo "Detected version: $version"
                  echo "version=$version" >> $GITHUB_OUTPUT

            - name: Check if tag already exists
              id: check_tag
              run: |
                  git fetch --tags
                  if git rev-parse "refs/tags/${{ steps.extract.outputs.version }}" >/dev/null 2>&1; then
                    echo "Tag already exists. Skipping release."
                    echo "skip=true" >> $GITHUB_OUTPUT
                  else
                    echo "skip=false" >> $GITHUB_OUTPUT
                  fi

            - name: Create GitHub release
              if: steps.check_tag.outputs.skip == 'false'
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ steps.extract.outputs.version }}
                  name: ${{ steps.extract.outputs.version }}
                  body: |
                      Auto release for version ${{ steps.extract.outputs.version }}.
                      Triggered by changes in severitium.user.js.
