name: Build Theme

on:
    workflow_dispatch:
    release:
        types: [created]

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install minifiers
              run: npm install -g terser clean-css-cli

            - name: Build and minify JS
              run: |
                  version="${{ github.ref_name }}"
                  mkdir -p "release/data/$version"
                  find src -path "src/_Additional" -prune -o -name "*.min.js" -print \
                    | xargs cat > "release/data/$version/script.release.min.js"
                  terser "release/data/$version/script.release.min.js" -c -m -o "release/data/$version/script.release.min.js"

            - name: Build and minify CSS
              run: |
                  version="${{ github.ref_name }}"
                  find src -path "src/_Additional" -prune -o -name "*.min.css" -print \
                    | xargs cat > "release/data/$version/style.release.min.css"
                  cleancss -o "release/data/$version/style.release.min.css" "release/data/$version/style.release.min.css"

            - name: Commit and push release
              run: |
                  version="${{ github.ref_name }}"
                  git fetch origin main
                  git checkout main
                  git pull

                  echo -e "$version\nbuild: update release js/css" > .git/COMMIT_EDITMSG

                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

                  git add release/
                  git commit -F .git/COMMIT_EDITMSG
                  git push origin main
